[package]
name = "dubit-limited/vr46"
version = "2.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@0.3.0"
Signal = "sleitnick/signal@1.1.0"
Comm = "sleitnick/comm@0.3.1"
TableUtil = "sleitnick/table-util@1.1.1"
Promise = "evaera/promise@^4"
